apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: redis-tls
  namespace: redis
spec:
  secretName: redis-tls
  duration: 2160h # 90 days
  renewBefore: 720h # 30 days
  dnsNames:
    - redis.homelab.courtroom.cloud
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
    group: cert-manager.io
